# Generated by Django 4.2.7 on 2023-12-11 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="content",
            new_name="text",
        ),
    ]
