# Generated by Django 4.2.7 on 2023-12-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_alter_comments_parent_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="comments",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.comments",
            ),
        ),
    ]
